name: Deploy to Railway

on:
  push:
    branches:
      - main  # Cambia esto si usas otra rama para despliegues

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Checkout del código
      - name: Checkout code
        uses: actions/checkout@v3

      # Paso 2: Configurar Java (ajusta la versión según tu proyecto)
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Paso 3: Instalar Railway CLI
      - name: Install Railway CLI
        run: |
          curl -sSL https://railway.app/install.sh | sh
          echo "$HOME/.railway/bin" >> $GITHUB_PATH

      # Paso 4: Vincular el Proyecto de Railway (Método Opcional)
      - name: Link Railway Project
        env:
          RAILWAY_API_TOKEN: ${{ secrets.RAILWAY_API_TOKEN }}
          RAILWAY_PROJECT: ${{ secrets.RAILWAY_PROJECT_ID }}
          RAILWAY_SERVICE: ${{ secrets.RAILWAY_SERVICE_ID }}
        run: |
          railway login --api-key $RAILWAY_API_TOKEN
          railway link --project $RAILWAY_PROJECT --service $RAILWAY_SERVICE

      # Paso 5: Desplegar con Railway
      - name: Deploy to Railway
        run: railway up --ci
        env:
          RAILWAY_API_TOKEN: ${{ secrets.RAILWAY_API_TOKEN }}













