# .github/workflows/cd.yml

name: CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write  # Necesario para publicar en GitHub Container Registry

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # O 'adopt' si prefieres AdoptOpenJDK
          java-version: '17'

      - name: Build with Maven
        run: mvn clean package

      - name: Build Docker image
        run: docker build -t ghcr.io/${{ github.repository_owner }}/${{ github.repository_name }}:latest .

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image to GitHub Container Registry
        run: docker push ghcr.io/${{ github.repository_owner }}/${{ github.repository_name }}:latest

      - name: Install Railway CLI
        run: |
          curl -sL https://railway.app/install.sh | sh
          export PATH="$HOME/.railway/bin:$PATH"

      - name: Deploy to Railway
        env:
          RAILWAY_API_TOKEN: ${{ secrets.RAILWAY_API_TOKEN }}
        run: |
          railway login --token $RAILWAY_API_TOKEN
          railway up --build ghcr.io/${{ github.repository_owner }}/${{ github.repository_name }}:latest --env production

